name:                deriving-gcompare
version:             0.1.0.0
github:              "ollef/deriving-gcompare"
license:             BSD3
author:              "Olle Fredriksson"
maintainer:          "fredriksson.olle@gmail.com"
copyright:           "2018 Olle Fredriksson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/githubuser/deriving-gcompare#readme>

dependencies:
- base >= 4.7 && < 5
- dependent-sum
- template-haskell
- th-utilities

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -funbox-strict-fields

library:
  source-dirs: src

tests:
  deriving-gcompare-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deriving-gcompare
